events { worker_connections 1024; }

http {
    # Define the group of servers to balance traffic across
    upstream my_cluster {
        # Docker automatically maps the service name 'app' 
        # to all running container IP addresses under that service
        server sneat-dashboard-app-1:80;
        server sneat-dashboard-app-2:80;
        server sneat-dashboard-app-3:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://my_cluster;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $http_host;
            add_header X-Upstream-Addr $upstream_addr always;
        }
    }
}
