name: CI

on:
  push: # Runs when commits are pushed to any branch, including a newly pushed branch.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        run: cp .env.example .env

      - name: Start containers
        run: docker compose up -d app mysql

      - name: Show MySQL logs
        if: always()
        run: docker compose logs mysql

      - name: Show container status
        if: always()
        run: docker compose ps

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      - name: Run migration
        run: docker compose exec -T app php artisan migrate

      - name: Generate app key
        run: docker compose exec -T app php artisan key:generate

      - name: Run tests
        run: docker compose exec -T app php artisan test

      - name: Stop containers
        if: always()
        run: docker compose down -v
